# Basics of Game Theory

## Nature of Games

We'll think of a game as any situation where multiple players have to make some decisions, and the outcome they get is a function of (perhaps among other things) the decisions that each make. So understood, that's a very large class of situations. Indeed, game theory has been used to analyse any number of real-world interactions, as you might expect from a definition so broad.

We're going to start our focus on a special class of games, two player simultaneous move games. The term 'two player' probably obvious; it means that we're looking at games where just two players are involved. Simultaneous move games are where each player only gets to make one decision, or move. Each player makes that decision in ignorance of what the other players have decided. And once the decisions are made, the payoffs for each player can be revealed.

This feels like a very narrow class of games. After all, most interactions involve multiple moves by at least one player, or at least players making moves at different times. But there is a good sense in which this is not a particularly tight restriction. Think of a game where the players make multiple moves, like chess. We can imagine a game between two chess super-computers that have planned, in advance, what they will do at every possible stage of the game. Call such plans **strategies**. If two such computers played, they would in a sense each just have to make one, simultaneous, move, namely to announce their strategies. Then it would be relatively trivial to work out the result of the game from the strategies announced.

In practice, this isn't really possible with current technology. There are too many possible states of the board, even in a restricted game like chess, for a computer to have planned for every possible eventuality. But we can imagine such complete strategies for simple games like tic-tac-toe, and even for moderately complicated games like checkers.

For these reasons, when we are discussing simultaneous move games, we will often refer to the players' options as *strategies*. The representation of the game as an $n \times m$ matrix, where one player (represented on rows) has $n$ options, and the other player (represented on columns) has $m$ options, is sometimes called a **normal form** representation of a game and sometimes called a **strategic form** representation. And we'll start off with these matrix representations. When we complicate things by explicitly representing time in the game, we'll call the representation the **extensive form** representation of the game.

## Utility

Here is a representation of an important kind of two player simultaneous move game.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | 3, 3 | 0, 5 |
|         +---+------+------+
|         | Y | 5, 0 | 1, 1 |
+---------+---+------+------+

Each player, Row and Col, has two options: X and Y. The payoffs, given their moves, are as follows:

- If both play X, both get 3.
- If both play Y, both get 1.
- If one plays X and the other Y, then the one who plays X gets 0, and the one who plays Y gets 5.

What does it mean to say that they 'get' 0, 1, 3 or 5? It means that the **utility** they get from the payout is that amount. For any given game, the results for the players can be specified in two related, but importantly distinct, ways.

- We can specify their **payouts**. These are the concrete things the players get. In the first example in Leyton-Brown and Shoham, the payout the players get is that their average packet delay is a certain amount. Payouts might be specified in dollars, or grades, or goals, or any thing we like.

- Alternatively, we can specify the **utility** each player gets from their payout.

Utility is a somewhat technical, somewhat theoretical, notion.

The idea is to numerically measure how good an outcome is to an agent. It is meant to sum up every aspect of outcomes that agents care about. For instance, if an agent cares a lot about their friend's payout, then their utility in an outcome will be a function not just of their own payout, but of their friend's. So if her payout is \$$x$ and her friend's payout is \$$y$, then her utility might equal $x + 0.5y$. This would represent that she cares about her friend's payout, but cares a bit more (well, twice as much) about her own outcome.

The substantive assumption here is that we can sensibly map the goodness of outcomes onto the real numbers. This assumes that goodness is, in a sense, one-dimensional. For any two numbers $x, y$, $x$ is either greater than, less than, or equal to $y$. So one assumption we're making is that any two outcomes are comparable in this way. We're also assuming that we can compare the distance between pairs of outcomes. For any numbers $x_1, y_1, x_2, y_2$, we can ask which of $x_1 - y_1$ and $x_2 - y_2$ is greater. So if we can map outcomes onto numbers, then for any four outcomes, we can ask if the difference between the first two in goodness is more than, less than, or the same as, the difference in goodness between the last two. This isn't an absurd assumption, though it can seem a little arbitrary in some cases.

Although we assume that the goodness to an agent of outcomes can be mapped onto numbers, we do not assume that there is a unique way to do this mapping. In fact there are two degrees of freedom in choosing a mapping. The outcome that gets utility zero can be any point is convenient to use. In practice, it is often convenient to give the status quo utility zero. But note this is arbitrary, we could use anything. The scale of the utility function is also arbitrary; we can multiply the utilities by a positive constant and it won't change their meaning.

Technically, if one utility function correctly represents an agent, then so will any other function generated from it by a positive affine transformation. So if $u_1$ is a utility function that correctly represents the agent, then so will the function $u_2$ defined as follows.

\begin{equation*}
u_2(X) = au_1(X) + b \text{, where }a\text{ is positive}.
\end{equation*}

 

What does it mean to say that a function $u$ correctly represents the agent? First, it means that the agent prefers $X$ to $Y$ just in case $u(X) > u(Y)$. Second, it means that for any $X, Y, Z$ the agent prefers $Y$ to a gamble that returns $X$ with probability $p$ and $Z$ with probability $1-p$ iff $u(Y) > pu(X) + (1-p)u(Z)$.

When it isn't stated otherwise, we will describe the outcomes of games in terms of the utility each agent gets. Sometimes we will have to just state what the payout is each agent gets, and the utility function will be either unknown, or will have to be figured out. But the default is that we will list the utility of each outcome.

## Four Examples of Games

We'll start with a very simple class of games: 2 player simultaneous move games where each player has 2 choices for their move. As we'll see, there is plenty of complexity within even this class.

## Prisoners' Dilemma

We've already seen a version of this game.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | 3, 3 | 0, 5 |
|         +---+------+------+
|         | Y | 5, 0 | 1, 1 |
+---------+---+------+------+

The general form of the game is given here, assuming $a > b > c > d$, and $2b > a + d$.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | $b$, $b$ | $d$, $a$ |
|         +---+------+------+
|         | Y | $a$, $d$ | $c$, $c$ |
+---------+---+------+------+

One characteristic of the game is that for each player, playing $Y$ is better than playing $X$ no matter what the other person does. That is, playing $Y$ **dominates** playing $X$; it is better no matter what. But, and this is what gives the game its distinctive character, it is better for both players if they both play $X$ than if they both play $Y$. (And in a repeated game it is better to always play $X$ than to alternate between the outcomes where players make opposite moves.) It is an interesting way to think about modeling situations where there are rewards to cooperation, but incentives to individualist behavior.

## Stag Hunt

The next game we'll look at is called Stag Hunt. We'll again do a version with commonly used numbers, then the general version.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | 5, 5 | 0, 4 |
|         +---+------+------+
|         | Y | 4, 0 | 2, 2 |
+---------+---+------+------+

The general version has $a > b > c > d$ and $b + c > a + d$

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | $a$, $a$ | $d$, $b$ |
|         +---+------+------+
|         | Y | $b$, $d$ | $c$, $c$ |
+---------+---+------+------+

Here the best outcome for all parties is the cooperative one. But if a player has no idea what the other player will do, and thinks it is 50/50 whether they will do the cooperative thing, then their best bet is to not cooperate.

The cute story behind this game comes from the eighteenth century political philosopher Jean-Jacques Rousseau. Imagine two people are setting out on the day's hunt, and are going to hunt stag or rabbits. Catching a stag will lead to more meat, but it is impossible with just one person. One person can catch a lot of rabbits, especially if no one else is hunting rabbits. In this case, X is joining the stag hunt, and Y is setting off on a solo rabbit hunt. It isn't as hard to get cooperative outcomes in this game as in Prisoners' Dilemma, but it takes some background trust.

## Battle of the Sexes

I don't particularly like the name of this one, but it is common enough that you probably should know it.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | 2, 1 | 0, 0 |
|         +---+------+------+
|         | Y | 0, 0 | 1, 2 |
+---------+---+------+------+

Here's the general version, with $a > b > c$,

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | $a$, $b$ | $c$, $c$ |
|         +---+------+------+
|         | Y | $c$, $c$ | $b$, $a$ |
+---------+---+------+------+

The thought is that both parties prefer coordination - making the same pick - to doing different things. But they differ on what they would like to coordinate on; Row would like to coordinate on X, and Column would like to coordinate on Y. The name comes from the version of the game where Row and Column are husband and wife, and X and Y are stereotypically male/female things to prefer doing. You can probably fill in your own example here.

## Chicken

Our last game is not for the faint of heart.

+:--------+--:+:----------:+:-----:+
|         |   | **Col**            |
+---------+---+------------+-------+
|         |   | X          | Y     |
+---------+---+------------+-------+
| **Row** | X | -100, -100 | 1, -1 |
|         +---+------------+-------+
|         | Y | -1, 1      | 0, 0  |
+---------+---+------------+-------+

The idea comes from a James Dean movie. Two cars are lined up facing each other at the end of a long straight. They start driving at each other. The drivers can either stay on the road (that's X), or swerve to the right (that's Y). If they both stay on the road, they die in a fiery inferno. If one swerves and the other stays, the one who stays wins the game, and the other loses. If they both swerve, the game is a draw.

Unlike the previous games we've looked at, there is no pure **equilibrium** to this game. That is, there is no point in the game where no one regrets their choice on finding out what the other players choose. There is an equilibrium to the game, it turns out, but getting to it requires a bit of background.

## Types of Games

Let $u(x, o)$ be the utility that player $x$ gets in outcome $o$. Then a two player game, with players $p_1, p_2$ is **zero-sum** if there is some constant $c$ such that for any outcome $o$, $u(p_1, o) + u(p_2, o) = c$. That is, however good an outcome is for $p_1$, it is equally bad for $p_2$, and vice versa. Pure competitions are zero-sum, though real zero-sum interactions are rare in the real world.

By convention, when a game is zero-sum, we rescale the utilities so the constant $c$ is 0. We always can do this - remember any positive affine transformation of the utility function doesn't change its meaning. That's why we can talk about zero-sum games, and not just constant sum games.

You might worry that whether a game is zero-sum or not depends on completely arbitrary choices about how to scale the utility functions. Strictly speaking, a game is zero-sum if there is *any* pair of utility functions that correctly represents the agents, and which makes the utility each gets from any outcome sum to a constant.

A game is **cooperative** if in any outcome, each player gets the same utility. As with the definition of zero-sum, it doesn't matter whether the game looks cooperative on every way of representing the utilities of the players, just if it looks cooperative on some representation.

## Dominant Strategies

Say that one player has available to them strategies $s_1, \dots, s_n$, and the other players have available to them collectively strategies $v_1, \dots, v_m$. In the case of a two player game, the strategies available to other players will just be strategies. But in games with more than two players, we'll think of the alternatives available to other players as *vectors*, with each dimension being a choice available to one of the other players. So $v_17$ might be that player 2 plays X, and player 3 plays Y, and player 4 plays Z, and player 5 also plays Z. Every one of these vectors specifies the choices of all other players in the game.

Let $u_x(s_i, v_k)$ be the utility that $x$, the player we're focussing on, gets if she plays $s_i$ and the others play $v_k$. Then strategy $s_i$ **strongly dominates** strategy $s_j$ if and only if the following condition is satisfied.

\begin{equation*}
\forall m: u_x(s_1, v_m) > u_x(s_2, v_m)
\end{equation*}

 

That is, no matter what the other players end up playing, $x$ will do better playing $s_1$ than playing $s_2$.

We'll say that strategy $s_i$ **weakly dominates** strategy $s_j$ if and only if the following condition is satisfied.

\begin{equation*}
\forall m: u_x(s_1, v_m) \geq u_x(s_2, v_m) \& \exists m: u_x(s_1, v_m) > u_x(s_2, v_m)
\end{equation*}

 

That is, playing $s_1$ can't do any worse than playing $s_2$, no matter what the others do, and it could do better.

## Dominance and Solving Games

Here is one simple way to make progress on a game.

1. Assume that no player will play a strongly dominated strategy.
2. Assume that every player will make a rational choice given that no player will play a dominated strategy.

The first step here lets us solve Prisoners' Dilemma. Since $Y$ dominates $X$, neither player will play $X$. So the solution to the game is that both players play $Y$. Here is another game that isn't solved by the first step, but is solved by the second step.

+:--------+--:+:----:+:----:+
|         |   | **Col**     |
+---------+---+------+------+
|         |   | X    | Y    |
+---------+---+------+------+
| **Row** | X | 2, 1 | 3, 0 |
|         +---+------+------+
|         | Y | 0, 0 | 1, 1 |
+---------+---+------+------+

Here Column has no dominant strategy; what's best for them to play is a function of what Row plays. But Row does have a dominant strategy. Whatever Column does, they are better off playing Y. So we should assume they will play Y. And given they play Y, Column should also play Y. So the solution to the game again is that both players play Y.

In later chapters, we'll look what happens when we iterate this idea. But first we need an introduction to probability theory.
