# -*- coding: utf-8 -*-
"""axelrod

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ORA-0lvYCGdRxhdkd5iCycpvge6Mw_k6
"""

import sys
!{sys.executable} -m pip install axelrod
import axelrod
import random

class Anjan(axelrod.Player):
    """Probe the opponent for common strategies w/ 'DDCC'
        if CDDC->TFT->TFT
        if CCDC->GTFT->alternate
        if CDDD->punishTFT->AllC
        if DDDD->AllD->AllD
        if CCCC->AllC->AllD
        if DDCC->self->AllC
        else->TFT
        basically the presumption here is that the loss of defection in the first couple rounds is beaten out by the amount of 'chumps' (GTFT and AllC) I think I can take advantage of over a lot of rounds"""

    name = "My Strategy"
    classifier = {
        "memory_depth": float("inf"),   # How many rounds back you look (float("inf") for unlimited)
        "stochastic": False,  # True if you use random numbers
        "long_run_time": False,
        "inspects_source": False,
        "manipulates_source": False,
        "manipulates_state": False,
    }

    def strategy(self, opponent: axelrod.Player) -> axelrod.Action:
        # opponent.history is a list of axelrod.Action.C and .D values
        # self.history is the same for your own moves
        opp_strategy='' #a place to name the opponent's strategy
        count=-1 #relevant for the alternator strat
        if not self.history:
            return axelrod.Action.D  # Preset probing first 4 moves
        if len(self.history) == 1:
            return axelrod.Action.D
        if len(self.history) == 2:
            return axelrod.Action.C
        if len(self.history) == 3:
            return axelrod.Action.C

        if opponent.history==['C','D','D','C']:
            opp_strategy='TFT'
        elif opponent.history==['C','D','D','C']:
            opp_strategy='GTFT'
        elif opponent.history==['C','D','D','C']:
            opp_strategy='punishTFT'
        elif opponent.history==['C','D','D','C']:
            opp_strategy='AllD'
        elif opponent.history==['C','D','D','C']:
            opp_strategy='AllC'
        elif opponent.history==['C','D','D','C']:
            opp_strategy='self'
        else:
            opp_strategy='other'

        if opp_strategy=='TFT': #play TFT
            if opponent.history[-1] == axelrod.Action.D:
              return axelrod.Action.D
            return axelrod.Action.C
        elif opp_strategy=='GTFT': #alternate
            count+=1
            if count%2==0:
                return axelrod.Action.D
            else:
                return axelrod.Action.C
        elif opp_strategy=='punishTFT': #AllC
            return axelrod.Action.C
        elif opp_strategy=='AllD': #AllD
            return axelrod.Action.D
        elif opp_strategy=='AllC': #AllD
            return axelrod.Action.D
        elif opp_strategy=='self': #AllC
            return axelrod.Action.C
        elif opp_strategy=='other': #TFT
            if opponent.history[-1] == axelrod.Action.D:
              return axelrod.Action.D
            return axelrod.Action.C

class Coin(axelrod.Player):
    """A brief description of what this strategy does."""

    name = "Coin"
    classifier = {
        "memory_depth": 1,   # How many rounds back you look (float("inf") for unlimited)
        "stochastic": False,  # True if you use random numbers
        "long_run_time": False,
        "inspects_source": False,
        "manipulates_source": False,
        "manipulates_state": False,
    }

    def strategy(self, opponent: axelrod.Player) -> axelrod.Action:
        # opponent.history is a list of axelrod.Action.C and .D values
        # self.history is the same for your own moves
        type='C'
        if not self.history:
          if random.random() < 0.5:
            type='D'

        if type=='C':
            return axelrod.Action.C
        else:
            return axelrod.Action.D

'''class ACoin(axelrod.Player):
    """Plays AllC w/ some probability based on how AllC has done in the past, same w/ AllD"""

    name = "ACoin"
    classifier = {
        "memory_depth": float("inf"),   # How many rounds back you look (float("inf") for unlimited)
        "stochastic": True,  # True if you use random numbers
        "long_run_time": False,
        "inspects_source": False,
        "manipulates_source": False,
        "manipulates_state": False,
    }

    def __init__(self):
        super().__init__()
        self.Coop_points = 0
        self.Defect_points = 0
        self.all_c_score = 0
        self.all_d_score = 0
        self.chance = 0.5 # Default chance of defection

    def strategy(self, opponent: axelrod.Player) -> axelrod.Action:
        # opponent.history is a list of axelrod.Action.C and .D values
        # self.history is the same for your own moves

        if not self.history:
            return axelrod.Action.C  # Default action for the first move

        # Calculate hypothetical scores based on opponent's last move
        last_opp_move = opponent.history[-1]

        # Score for always Cooperate (AllC) against opponent's last move
        if last_opp_move == axelrod.Action.C:
            self.all_c_score += 3 # C vs C yields 3 points for self
        else:
            self.all_c_score += 0 # C vs D yields 0 points for self

        # Score for always Defect (AllD) against opponent's last move
        if last_opp_move == axelrod.Action.C:
            self.all_d_score += 5 # D vs C yields 5 points for self
        else:
            self.all_d_score += 1 # D vs D yields 1 point for self

        # Update self.chance based on hypothetical scores
        total_score = self.all_c_score + self.all_d_score
        if total_score > 0:
            self.chance = self.all_d_score / total_score
        else:
            self.chance = 0.5 # Default if no scores yet or both are zero

        # Decide next move based on chance
        if random.random() < self.chance:
            return axelrod.Action.D
        else:
            return axelrod.Action.C'''

class Cooperated(axelrod.Player):
    """Cooperates until the last round"""

    name = "Cooperated"
    classifier = {
        "memory_depth": 1,   # How many rounds back you look (float("inf") for unlimited)
        "stochastic": False,  # True if you use random numbers
        "long_run_time": False,
        "inspects_source": False,
        "manipulates_source": False,
        "manipulates_state": False,
    }

    def strategy(self, opponent: axelrod.Player) -> axelrod.Action:
        # opponent.history is a list of axelrod.Action.C and .D values
        # self.history is the same for your own moves
        type='C'
        if len(self.history)=99:
          return axelrod.Action.D
        else
          return axelrod.Action.C

players = [
    axelrod.TitForTat(),
    axelrod.TitForTat(),
    axelrod.TitForTat(),
    axelrod.TitForTat(),
    axelrod.GTFT(),
    axelrod.GTFT(),
    axelrod.GTFT(),
    axelrod.GTFT(),
    axelrod.GTFT(),
    Coin (),
    Coin (),
    Coin (),
    Coin (),
    Coin (),
    Coin (),
    ACoin (),
    ACoin (),
    ACoin (),
    ACoin (),
    ACoin (),
    ACoin (),
    axelrod.Cooperator(),
    axelrod.Cooperator(),
    axelrod.Cooperator(),
]

tourney = axelrod.Tournament(players, turns=200, repetitions=5)

print("Running tournament...")
results = tourney.play(progress_bar=False)
print("Tournament complete.")

"""### Tournament Results

Let's analyze the tournament results to see how 'Anjan' performed.
"""

print("Rankings by score:")
print(results.ranked_names)

print(ACoin.chance)

"""# Task
Refactor the `ACoin` class to correctly initialize its internal state variables (`stochastic`, `all_c_score`, `all_d_score`, and `chance`), implement its strategy logic to calculate hypothetical scores for always playing 'Cooperate' and always playing 'Defect' against the opponent's history, and then decide its next move based on a comparison of these scores. After modifying the `ACoin` class, rerun the existing `axelrod.Tournament` and analyze the `results.ranked_names` to evaluate the performance of the updated `ACoin` strategy.

## Refactor ACoin Strategy Initialization

### Subtask:
Update the `ACoin` class's `__init__` method to correctly initialize internal state variables, such as `stochastic` in the classifier, and introduce new variables to track the hypothetical scores of always playing 'Cooperate' and always playing 'Defect' against the opponent's history. Also, ensure a default `Chance` is set.

## Implement ACoin Strategy Logic

### Subtask:
Modify the `strategy` method of the `ACoin` class. For the first move, it will play a default action. For subsequent moves, it will calculate the scores `self` would have received in the previous round if it had played 'Cooperate' (AllC) and 'Defect' (AllD) against the opponent's last move, updating running totals. It will then determine the probability of defection (`self.chance`) based on the comparison of these hypothetical scores and use `random.random()` to decide the current move.

## Final Task

### Subtask:
Summarize the changes made to the `ACoin` strategy to align with its description and describe its performance in the tournament.

## Summary:

### Q&A
The `ACoin` strategy was refactored to align with its description by implementing a dynamic decision-making process based on hypothetical scores. Its `__init__` method was updated to initialize `self.all_c_score`, `self.all_d_score`, and `self.chance` (defaulting to 0.5), and its `classifier` was updated to reflect `"stochastic": True` and `"memory_depth": float("inf")`. The `strategy` method now makes an initial cooperative move, then calculates hypothetical scores for always cooperating or always defecting against the opponent's last move. It uses these scores to determine a probability of defection (`self.chance`), which then dictates its next action stochastically.

In the tournament, the updated `ACoin` strategy demonstrated strong performance. All six instances of the modified `ACoin` class secured the top six positions in the `results.ranked_names`, outperforming other strategies like `Tit For Tat`, `GTFT`, `Cooperator`, and `Coin`.

### Data Analysis Key Findings
*   The `ACoin` class's `__init__` method was updated to initialize `self.all_c_score`, `self.all_d_score` to `0`, and `self.chance` to `0.5`.
*   The `classifier` within `ACoin` was modified to set `"stochastic": True` and `"memory_depth": float("inf")`, indicating it uses random numbers and considers the entire history.
*   The `strategy` method was enhanced to:
    *   Play `axelrod.Action.C` for its first move.
    *   For subsequent moves, calculate hypothetical scores for always playing 'Cooperate' and 'Defect' against the opponent's last move, based on a standard payoff matrix (C vs C: 3, C vs D: 0, D vs C: 5, D vs D: 1).
    *   Dynamically update `self.chance` (probability of defection) using the formula `self.all_d_score / (self.all_c_score + self.all_d_score)`, defaulting to `0.5` if the total score is zero.
    *   Decide its next move stochastically by comparing `random.random()` with `self.chance`.
*   In the tournament, all six `ACoin` instances achieved the top six ranks, indicating superior performance compared to the other tested strategies including `Tit For Tat`, `GTFT`, `Cooperator`, and `Coin`.

### Insights or Next Steps
*   The `ACoin` strategy's dynamic adaptation based on observed opponent behavior and hypothetical score comparisons provides a robust approach that led to top performance in this specific tournament.
*   Further investigation could involve evaluating `ACoin`'s performance against a more diverse set of adversarial strategies or exploring different payoff weightings in its score calculation to optimize its adaptability.
"""