---
title: "Game Theory and Social Choice"
subtitle: "Lecture 2: Decision Theory Revision"
author: "Brian Weatherson"
date: "September 3, 2026"
---

# Expected Utility

## Basic Decision Theory

The basic structure of a decision problem has three parts:

1. Acts
2. States
3. Payoffs

. . .

The aim is to identify which acts are worth choosing.

## Payoffs

We assume that the chooser has a **utility function**, usually written $u$.

This is a function from **outcomes**, i.e., act-state pairs, to **real numbers**.

Some people take these to measure **how good** the outcome is for the chooser; others take them to measure how much the chooser **desires** the outcome.

The simplest approach is to presuppose the view on which these are the same thing, the so-called **preference-satisfaction theory** of welfare.

This theory is controversial (to put it mildly) but we'll simply assume it.

## Payoffs

Even still, it's not obvious why payoffs should be real numbers.

Saying that utilities are real numbers has two implications for their structure.

First, any two utilities are comparable. Either the first is greater, or the second is greater, or the two are equal.

Second, the following ratio has to be finite, as long as $u(a) > u(b) > u(c)$.

$$
\frac{u(a) - u(b)}{u(b) - u(c)}
$$

## Utility

The only thing we use utilities for is asking which act has the highest expected utility. Absolute utilities do not do any work, only comparisons between utilities. If you changed the utility of all outcomes by a constant, *nothing would change*.

One slight oddity of this way of thinking about utilities is that utility level **zero** is not of any particular significance.

All that's going to matter are differences between utilities, and ratios of these differences.

By default, we'll set 0 as the utility of the status quo, but that's just a convention with no content.

## Probability

When you set up a decision problem, you have to say what the probabilities are of every state.

I imagine that everyone here knows at least roughly what probabilities are. But just to have everything on the record, a probability function (as we're using the notion) is a function $\Pr$ from propositions to real numbers in $[0, 1]$ satisfying:

$$
\begin{align*}
&\Pr(\top) = 1 \\
&\Pr(\bot) = 0 \\
&\text{If }\neg(A \wedge B) \text { is a theorem then }\Pr(A \vee B) = \Pr(A) + \Pr(B)
\end{align*}
$$

## Conditional Probability

We also define a notion of conditional probability.

Read $\Pr(A | B)$ as the probability of $A$ *given* $B$. We take this to satisfy:

$$
\Pr(A | B)\Pr(B) = \Pr(A \wedge B)
$$

. . .

Sometimes this is taken to be a **definition** of $\Pr(A | B)$ after dividing both sides by $\Pr(B)$. But this leads to division by 0 complications; we won't take this to be definitive.

## Conditionalisation

Probabilities change with evidence. The usual rule for how they change is called **conditionalisation**. It says that probabilities should update as follows.

$$
\Pr_E(H) = \Pr(H | E)
$$

In words, the probability of hypothesis $H$ after getting evidence $E$ is the old conditional probability of $H$ given $E$.

. . .

Note that this is a philosophical claim, not a mathematical theorem. And we'll also be quibbling with it a bit around the edges.

## Expected Value

Assuming that $\Pr$ measures the probability of the states, then the **expected value** of each action is given by this formula:

$$
E(A) = \sum_{S \in \mathcal{S}} \Pr(S)u(A \wedge S)
$$

That is, we sum across the states, in each case multiplying the probability of the state by the utility of performing that action in that state.

. . .

Then the one and only rule is **Maximise expected utility**!

## Example

|   |   Rain (Pr = 0.6)  |  Dry (Pr = 0.4) |
|---:|:---:|:---:|
| Take Umbrella  |   6    |   8   |
| Leave Umbrella |   0    |   10  |

: The umbrella problem again {#tbl-umbrella-again}

. . .

The expected utility of taking the umbrella is $6 \times 0.6 + 8 \times 0.4 = 6.8$.

The expected utility of leaving the umbrella is $0 \times 0.6 + 10 \times 0.4 = 4$.

Take the umbrella!


# What Are States

## A Puzzle about Causation

In _Henry V_, Shakespeare has King Henry give the following argument to his staff before Agincourt. The background is that the staff want to wait for reinforcements, but Henry wants to charge into battle. Here is his argument (slightly formalised, but only a little).

1. If we're going to win, it's better to win with fewer men, because we'll get more praise.
2. If we're going to lose, it's better to lose with fewer men, because it will involve a smaller loss.
3. So, either way, we should battle rather than wait for reinforcements.

. . .

I'm no military planner, but that strikes me as the worst argument in the entire history of military planning, and frankly I think it's slanderous that Shakespeare attributed it to Henry.

## A Puzzle about Causation

But you might think it looks like a good argument once you formalise it using these tables.

|     |    Win (Pr = $w$)   |   Lose (Pr = $1-w$)  |
|---:|:---:|:----:|
| Battle |  $a_1$   |  $a_2$   |
| Reinforce   |  $a_3$   |   $a_4$  |

: King Henry's decision {#tbl-agincourt}

. . .

The premises say, somewhat plausibly, that $a_1 > a_3$, and $a_2 > a_4$.

## A Puzzle about Causation

Then plugging in the formula for expected value, we get

$$
\begin{align*}
E(B) &= wa_1 + (1-w)a_2 \\
E(R) &= wa_3 + (1-w)a_4
\end{align*}
$$

And given that both $w$ and $1-w$ are non-negative, with at least one positive, and $a_1 > a_3$, and $a_2 > a_4$, it follows that $E(B) > E(R)$.

. . .

This is an absurd result; what's gone wrong?

## A Puzzle about Causation

The problem is that there is no such thing as *the* probability of winning or losing.

. . .

There is the probability of winning with reinforcements, and the probability of winning without reinforcements, and they are, crucially, different.

## A Puzzle about Causation

In philosophy, the main way people react to this is by **changing the formula** for expected value.

Or, more precisely, the main way*s* that people react to this is by changing the formula, for there are two main suggestions for what change we should make.

. . .

One approach, called **Evidential Decision Theory**, says that instead of $\Pr(S)$, you should use $\Pr(S | A)$.

Another approach, sometimes called **Causal Decision Theory** (though that name is used for many different theories), says that you should use $\Pr(A \rightarrow S)$, for some understanding of $\rightarrow$.

## A Puzzle about Causation

In game theory, the standard way to handle this problem is to put a **constraint on what counts as a state**.

In particular, it's only a properly formed problem if the acts and the states are causally independent.

This basically ends up being a version of Causal Decision Theory, though perhaps not exactly the same version. (Just how close to true this 'basically' claim is turns out, I think, to be an enormous question; not one we'll address here.)

## Newcomb's Problem

I introduced two possible changes to the expected value formula to handle the Henry V problem. They say the same thing to Henry, _Don't attack!_, but they say different things in the case called **Newcomb's Problem** (named after the physicist who introduced it to philosophers).

:::{.callout-note appearance="minimal"}
Human will be presented with two boxes, and will be told they can either take one box, the left one, or two boxes (i.e., both of them). The right hand box has \$1,000 in it. The left hand box won't be opened until a decision is made. A demon, who is very good at predictions, has predicted human's choice. If Demon predicted human would take 1 box, \$1,000,000 was put in the left box. If Demon predicted human would take 2 boxes, nothing was put in the left box.
:::

## Newcomb's Problem

The puzzle here is that there seem to be good arguments for each option.

1. People who take one box tend to get a million dollars; people who take two boxes tend to get a thousand dollars. It's better to get a million!
2. Whatever demon did, human will get \$1,000 more if they take both boxes. Anyone who knew what was in the left box would tell human to take both boxes, whatever is there, and human knows this.

## Newcomb's Problem

We're *not* going to resolve this problem here. I just want you to note three things.

1. If you calculate expected utilities with conditional probabilities, you get the 1 box, Evidential, theory. If you use probabilities of (subjunctive) conditionals, you get the 2 box, Causal, theory.
2. Insisting on acts and states being causally separate and then using the simple theory for expected utility also leads to the 2 box answer.
3. This is all going to be related to what we say about Prisoner's Dilemma.  

# Some Puzzles

## The Allais Paradox {#sec-allais}

- In the expected utility formula, there is no place for the intuitive preference for safe outcomes over risky outcomes.
- The orthodox view, which I share, is that this is accounted for entirely in the mapping between physical outcomes and utilities.
- But there is a famous argument, due to the French economist (and 1998 Nobel Prize winner) Maurice Allais that this can't do the job.

## A Pair of Choices

Allais imagines someone making two pairwise choices. Here is the first choice.

- **1A**: \$1,000,000, guaranteed.
- **1B**: a 1% chance of \$0, an 89% chance of \$1,000,000, and a 10% chance of \$5,000,000.

. . .

How many people think it's at least rationally permissible to take **1A**?

## A Pair of Choices

Here is the second choice.

- **2A**: an 89% chance of \$0, and an 11% chance of \$1,000,000.
- **2B**: a 90% chance of \$0, and a 10% chance of \$5,000,000.

. . .

How many people think it's at least rationally permissible to take **2B**?

. . .

How many people think it's both rationally permissible to take **1A** over **1B**, and to take **2B** over **2A**?

## Allais' Argument

1. It is rationally permissible to take **1A** over **1B**, and to take **2B** over **2A**.
2. According to expected utility theory, it is not rationally permissible to take **1A** over **1B**, and to take **2B** over **2A**.
3. Therefore, expected utility theory is wrong.

. . .

Can anyone see what the argument for premise 2 is?

## The Argument for Premise 2

Write $x$ for $U(\$5\text{M})$, $y$ for $U(\$1\text{M})$ and $z$ for $U(\$0)$. Preferring **1A** to **1B** means 

\begin{align*}
&nbsp; y &> 0.01z + 0.89y + 0.10x
&\therefore 0.11y - 0.10x - 0.01z &> 0
\end{equation*}

Preferring **2B** to **2A** means

\begin{align*}
E(U(2A)) - E(U(2B)) &= (0.11y + 0.89z) - (0.10x + 0.90z) &< 0\\
&\therefore 0.11y - 0.10x - 0.01z &<0
\end{align*}

## Ellsberg {#sec-ellsberg}

- An American, Daniel Ellsberg, who went on to play a famous role in the anti-Vietnam war movement, developed a similar example, also involving a pair of pairwise choices.
- An urn has 90 marbles in it. 
- The subject is told that 30 marbles are red, and the other 60 are a mix of black and yellow. 
- They are not told what the mixture is. 
- They will be offered a choice between two bets, which have the same return, say \$10 if you win, and \$0 if you lose. 

## Ellsberg's Pair of Choices

Here is the first choice.

- **1A**: You win if the marble is red, and lose otherwise.
- **1B**: You win if the marble is black, and lose otherwise.

. . .

How many people think it's at least rationally permissible to take **1A**?

## Ellsberg's Pair of Choices

Here is the second pair

- **2A**: You win if the marble is red or yellow, and lose otherwise.
- **2B**: You win if the marble is black or yellow, and lose otherwise.

How many people think it's at least rationally permissible to take **2B**?

. . .

How many people think it's both rationally permissible to take **1A** over **1B**, and to take **2B** over **2A**?

## Varieties of Sure Thing

::: {.callout-tip title="Value of Irrelevant Alternatives"}
Consider any choice between lotteries **A** and **B** where there is some possibility where the two options return the same amount, and you prefer **A** to **B**. Changing the lottery simply by changing that common amount, without making any other changes, shouldn't change your preferences. All that matters it that you get the same amount in that outcome, not what that 'same amount' is.
:::

The intuitions that both Allais and Ellsberg are trying to draw out imply that this principle is *false*.

## Differences Between the Arguments

- The Allais paradox suggests that we are wrong to say that all attitudes to risk are accounted for by declining marginal utility. 
- The Ellsberg paradox suggests that we are wrong to act as if everyone has a probability function in their head. 

. . .

Think about how you'd do a version of the algebraic argument that **1A**/**2B** is inconsistent in the Ellsberg case.

## Ellsberg and Numerical Probability

- In expected utility, theory everyone has a probability for every important possibility in their head. 
- Assume the chooser assigns probability $y$ to the drawn marble being yellow. 
- The probability of **1A** winning is 1/3, and the probability of **1B** winning is 2/3-$y$, so if they prefer **1A** to **1B**, it follows that $y$ is greater than 1/3. 
- The probability of **2A** winning is 1/3+$y$, and the probability of **2B** winning is 2/3. So $y$ is less than 1/3, contradicting the claim that it is greater.

## Imprecise Probability

- The response that Ellsberg and others gave to this argument is not to question the algebra, or to question the appeal to expected utility. 
- It's to question the very assumption that there is such a thing as $y$. 
- Or, in some versions, to question the assumption that it is a *number*. 
- The modern version of this is the theory of _imprecise probability_, and several people in the UM philosophy department, most notably Jim Joyce, have developed versions of this approach.


# Dynamic Choice

## Dynamic Choice

*Maximise expected utility* is a claim about what you should do in a one-shot choice.

How does it extend to choices over time?

## Two Theories

It turns out there are two prominent answers:

1. The **resolute** theory says that if you are going to face a series of choices, all that matters is that you pick a plausible strategy, and stick to it.
2. The **sophisticated** theory says that you should pick a rational choice at each node, and you should predict you will make rational choices at future nodes, and make choices that maximise expected utility given those constraints.

## A Third Approach

There is a much less popular third approach, called **conservative** choice. It has two components.

- Like the resolute theory, it says that one should pick a strategy at the start which makes sense and stick with it.
- Like the sophisticated theory, it says that this theory should continue to make sense at each subsequent node. It does not say this choice has to be **best**, just that it has to be **permissible**.
- Equivalently, it adds to the sophisticated theory the view that one must know what one will do at later nodes, not just that one will be rational.

## The Toxin Puzzle

We won't be covering this in detail here, but one way to possibly tease these apart is via a puzzle from a former Michigan philosopher, Gregory Kavka.

- There is some substance which is deeply unpleasant to drink; it will make you sick for several days, but has no long-term consequences
- If you were offered a million dollars to drink it, you totally would. It's not *that* unpleasant.
- But that's not what you are offered.

## The Toxin Puzzle

Instead, you are offered the following deal.

- You'll get a million dollars if, at midday tomorrow, you intend to drink the toxin at 6pm that night.
- If you do, you'll get the money straight away.

## Puzzle

On the one hand, it seems like this is a good deal.

On the other hand, how can you get the money? If you have the money already, you won't be motivated to drink.

So you won't really intend to drink, so in fact you won't get it after all.

## For Next Time

We'll start working on simple games.

<!--
Basic picture, EU maximisation
1. What are probabilities - additive normalised measures; explain both parts - motivate with accuracy dominance
2. What are utilities - we're just going to take them to be preferences; very big picture questions about whether that's right
3. State action links
    - Henry V puzzle
    - Solution 1: Insist that states are causally independent of actions; usually enforced temporally with no backwards causation assumption
    - Solution 2: Use conditional probabilities rather than absolute probabilities
    - These come apart in Newcomb
    - Also come apart in my signaling game, but in other direction, we need to say more about signaling to make that work
    - We're going to assume solution 1 here; but note this will come up from time to time
4. Puzzles
    - No upper bound, e.g., days in heaven; assume finiteness
    - St Pete, also assume finiteness
    - Non-linear preferences; puzzles about sweetening; go over Harvey's example
    - Risk and Allais; maybe mention sure-thing
    - Uncertainty and Ellsberg; maybe mention imprecise credences
    - Computational difficulties; maybe mention traveling salesman
5. Dynamics
    - Two prominent solutions: resolute and sophisticated
    - Resolute says that you pick something and stick with it
    - Sophisticated says that you treat each decision as a wholly new thing
    - Kavka's puzzle as a way of teasing these two apart
    - We're going to see an intermediate option

Onto strategic choice
Say what a 2*2*2 game is
Explain the notation
Note the lack of probabilities
Instead we assume common knowledge of rationality - that is, the iterative conception of common knowledge as in Lewis
    - Will come back to this briefly later
In decision theory, there is no way to solve this problem, because there are no probabilities
    - But in game theory there is a solution
    - Assume that the other player is rational, so they will choose dominating option, and that settles what Row should do
-->