<!DOCTYPE html>
<html lang="en"><head>
<script src="../site_libs/clipboard/clipboard.min.js"></script>
<script src="../site_libs/quarto-html/tabby.min.js"></script>
<script src="../site_libs/quarto-html/popper.min.js"></script>
<script src="../site_libs/quarto-html/tippy.umd.min.js"></script>
<link href="../site_libs/quarto-html/tippy.css" rel="stylesheet">
<link href="../site_libs/quarto-html/light-border.css" rel="stylesheet">
<link href="../site_libs/quarto-html/quarto-syntax-highlighting-065a5179aebd64318d7ea99d77b64a9e.css" rel="stylesheet" id="quarto-text-highlighting-styles"><meta charset="utf-8">
  <meta name="generator" content="quarto-1.8.25">

  <meta name="dcterms.date" content="2026-03-25">
  <title>College as a Signal</title>
  <meta name="apple-mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no, minimal-ui">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reset.css">
  <link rel="stylesheet" href="../site_libs/revealjs/dist/reveal.css">
  <style>
    code{white-space: pre-wrap;}
    span.smallcaps{font-variant: small-caps;}
    div.columns{display: flex; gap: min(4vw, 1.5em);}
    div.column{flex: auto; overflow-x: auto;}
    div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
    ul.task-list{list-style: none;}
    ul.task-list li input[type="checkbox"] {
      width: 0.8em;
      margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
      vertical-align: middle;
    }
  </style>
  <link rel="stylesheet" href="../site_libs/revealjs/dist/theme/quarto-48377cb64f814fd5afecd050e3f13ab9.css">
  <link rel="stylesheet" href="custom_styles_css.css">
  <link href="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.css" rel="stylesheet">
  <link href="../site_libs/revealjs/plugin/quarto-support/footer.css" rel="stylesheet">
  <style type="text/css">
    .reveal div.sourceCode {
      margin: 0;
      overflow: auto;
    }
    .reveal div.hanging-indent {
      margin-left: 1em;
      text-indent: -1em;
    }
    .reveal .slide:not(.center) {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide.scrollable {
      overflow-y: auto;
    }
    .reveal .footnotes {
      height: 100%;
      overflow-y: auto;
    }
    .reveal .slide .absolute {
      position: absolute;
      display: block;
    }
    .reveal .footnotes ol {
      counter-reset: ol;
      list-style-type: none; 
      margin-left: 0;
    }
    .reveal .footnotes ol li:before {
      counter-increment: ol;
      content: counter(ol) ". "; 
    }
    .reveal .footnotes ol li > p:first-child {
      display: inline-block;
    }
    .reveal .slide ul,
    .reveal .slide ol {
      margin-bottom: 0.5em;
    }
    .reveal .slide ul li,
    .reveal .slide ol li {
      margin-top: 0.4em;
      margin-bottom: 0.2em;
    }
    .reveal .slide ul[role="tablist"] li {
      margin-bottom: 0;
    }
    .reveal .slide ul li > *:first-child,
    .reveal .slide ol li > *:first-child {
      margin-block-start: 0;
    }
    .reveal .slide ul li > *:last-child,
    .reveal .slide ol li > *:last-child {
      margin-block-end: 0;
    }
    .reveal .slide .columns:nth-child(3) {
      margin-block-start: 0.8em;
    }
    .reveal blockquote {
      box-shadow: none;
    }
    .reveal .tippy-content>* {
      margin-top: 0.2em;
      margin-bottom: 0.7em;
    }
    .reveal .tippy-content>*:last-child {
      margin-bottom: 0.2em;
    }
    .reveal .slide > img.stretch.quarto-figure-center,
    .reveal .slide > img.r-stretch.quarto-figure-center {
      display: block;
      margin-left: auto;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-left,
    .reveal .slide > img.r-stretch.quarto-figure-left  {
      display: block;
      margin-left: 0;
      margin-right: auto; 
    }
    .reveal .slide > img.stretch.quarto-figure-right,
    .reveal .slide > img.r-stretch.quarto-figure-right  {
      display: block;
      margin-left: auto;
      margin-right: 0; 
    }
  </style>
</head>
<body class="quarto-light">
  <div class="reveal">
    <div class="slides">

<section class="quarto-title-block center">
  <h1 class="title">College as a Signal</h1>

<div class="quarto-title-authors">
</div>

  <p class="date">2026-03-25</p>
</section>
<section>
<section class="title-slide slide level1 center">
<h1>The Fact to be Explained</h1>

</section>
<section class="slide level2">
<h2>A Striking Wage Gap</h2>
<p>Here is a well-documented empirical fact across almost every rich country: people who complete a college degree earn substantially more over their lifetimes than people who don’t.</p>
<div class="fragment">
<p>This isn’t subtle. In the US, the lifetime earnings gap is well over <strong>one million dollars</strong>.</p>
</div>
<div class="fragment">
<p>The gap is large enough, and consistent enough across countries, that it demands an explanation.</p>
</div>
</section>
<section class="slide level2">

<p>Earnings of Bachelor’s degree holders as a percentage of upper-secondary earnings (full-time workers, 2023 OECD data):</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: center;">Premium</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Chile</td>
<td style="text-align: center;">228%</td>
</tr>
<tr class="even">
<td style="text-align: left;">United States</td>
<td style="text-align: center;">164%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Hungary</td>
<td style="text-align: center;">148%</td>
</tr>
<tr class="even">
<td style="text-align: left;"><strong>OECD average</strong></td>
<td style="text-align: center;"><strong>140%</strong></td>
</tr>
<tr class="odd">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: center;">137%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: center;">134%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Korea</td>
<td style="text-align: center;">133%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Australia</td>
<td style="text-align: center;">130%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Denmark</td>
<td style="text-align: center;">112%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Norway</td>
<td style="text-align: center;">106%</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">
<h2>Data Source</h2>
<p>All these data are from the OECD. To see the original, search for “Earnings of workers relative to the earnings of workers with upper secondary educational attainment, by age group, gender and educational attainment level”.</p>
<p>That will get you a datafile with 150,000 data points across different countries over the last couple of decades. I’m pulling some highlights out of it.</p>
</section>
<section class="slide level2">

<p>The premium is not constant across <strong>age</strong>. In most countries, older workers show a <strong>larger</strong> gap between degree holders and non-degree holders.</p>
<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: left;">Country</th>
<th style="text-align: center;">25–34</th>
<th style="text-align: center;">35–44</th>
<th style="text-align: center;">45–54</th>
<th style="text-align: center;">55–64</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">United States</td>
<td style="text-align: center;">157%</td>
<td style="text-align: center;">167%</td>
<td style="text-align: center;">168%</td>
<td style="text-align: center;">172%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Switzerland</td>
<td style="text-align: center;">127%</td>
<td style="text-align: center;">136%</td>
<td style="text-align: center;">142%</td>
<td style="text-align: center;">137%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Korea</td>
<td style="text-align: center;">116%</td>
<td style="text-align: center;">131%</td>
<td style="text-align: center;">148%</td>
<td style="text-align: center;">159%</td>
</tr>
<tr class="even">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: center;">128%</td>
<td style="text-align: center;">138%</td>
<td style="text-align: center;">151%</td>
<td style="text-align: center;">144%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">OECD average</td>
<td style="text-align: center;">131%</td>
<td style="text-align: center;">140%</td>
<td style="text-align: center;">152%</td>
<td style="text-align: center;">149%</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>In Korea, the premium rises steadily from 116% to 159% across the working life. In the US, the rise is more modest but consistent.</p>
</div>
<div class="fragment">
<p>Switzerland shows the same gradient in compressed form: from 127% for the youngest cohort up to 142% at ages 45–54, with a modest pullback to 137% near retirement.</p>
</div>
</section>
<section class="slide level2">

<p>The age pattern turns out to be concentrated among <strong>male</strong> workers. For <strong>women</strong>, the Bachelor’s premium is much flatter across age.</p>
<table class="caption-top" style="width:100%;">
<colgroup>
<col style="width: 23%">
<col style="width: 17%">
<col style="width: 17%">
<col style="width: 20%">
<col style="width: 20%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: center;">Men 25–34</th>
<th style="text-align: center;">Men 45–54</th>
<th style="text-align: center;">Women 25–34</th>
<th style="text-align: center;">Women 45–54</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">United States</td>
<td style="text-align: center;">162%</td>
<td style="text-align: center;">180%</td>
<td style="text-align: center;">158%</td>
<td style="text-align: center;">159%</td>
</tr>
<tr class="even">
<td style="text-align: left;">Korea</td>
<td style="text-align: center;">116%</td>
<td style="text-align: center;">141%</td>
<td style="text-align: center;">123%</td>
<td style="text-align: center;">142%</td>
</tr>
<tr class="odd">
<td style="text-align: left;">United Kingdom</td>
<td style="text-align: center;">130%</td>
<td style="text-align: center;">154%</td>
<td style="text-align: center;">141%</td>
<td style="text-align: center;">151%</td>
</tr>
</tbody>
</table>
<div class="fragment">
<p>In the US, male degree holders gain 18 percentage points between ages 25–34 and 45–54. Female degree holders gain almost nothing (158% to 159%).</p>
</div>
<div class="fragment">
<p>The UK shows the same pattern more modestly: men gain 24 points, women gain 10. Korea is the partial exception, where both men and women see substantial growth in the premium with age.</p>
</div>
</section>
<section class="slide level2">
<h2>Gender Differences</h2>
<p>This is worth keeping in mind when we get to explanations. Whatever is causing the premium to rise with age, it seems to operate very differently for men and women.</p>
</section>
<section class="slide level2">
<h2>The Sheepskin Effect</h2>
<p>Before discussing explanations: there is a striking feature of the wage data that any good explanation must account for.</p>
<div class="fragment">
<p>Completing <strong>two or three years</strong> of college gives you very little of the wage premium. The premium kicks in when you <strong>finish</strong>, when you get the degree.</p>
</div>
<div class="fragment">
<p>This is sometimes called the <strong>sheepskin effect</strong> (after the old tradition of printing diplomas on sheepskin).</p>
</div>
<div class="fragment">
<p>It is hard to explain if college simply develops valuable skills, why would three years of skills suddenly be worth dramatically more the moment a fourth year is complete?</p>
</div>
</section>
<section class="slide level2">
<h2>The US “Some College” Anomaly</h2>
<p>The sheepskin effect is especially stark in the US.</p>
</section>
<section class="slide level2">

<div class="columns">
<div class="column" style="width:35%;">
<div class="quarto-figure quarto-figure-center">
<figure>
<p><img data-src="images/ed_attain.png"></p>
<figcaption>Educational Attainment in the US</figcaption>
</figure>
</div>
</div><div class="column" style="width:60%;">
<p>The US has an unusually large share of its population in the “some college, no degree” category. In most other countries, this group is too small to draw reliable conclusions from.</p>
<p>That makes the US a good place to test the sheepskin effect: there are millions of people who spent years in college but didn’t finish, and their wage premium over high school graduates is small.</p>
<p>Any explanation of the premium needs to explain why <strong>completion</strong> matters so much more than the years spent acquiring the degree.</p>
</div></div>
</section>
<section class="slide level2">
<h2>The Pattern by Age</h2>
<p>One more fact that will matter a great deal: the college wage premium is <strong>not constant across age</strong>.</p>
<div class="fragment">
<p>Among workers aged 25–34, the premium is real but relatively modest.</p>
</div>
<div class="fragment">
<p>Among workers aged 45–54, the premium is <strong>substantially larger</strong>.</p>
</div>
<div class="fragment">
<p>Whatever is causing the premium seems to grow more powerful, not less, as workers age and accumulate experience.</p>
</div>
</section>
<section class="slide level2">
<h2>Your Turn: First Conjectures</h2>
<p>Before we go any further, <strong>why do you think employers pay so much more for college graduates?</strong></p>
<div class="fragment">
<p>Take two minutes to discuss with a neighbor. Try to come up with at least two different explanations that could in principle be true.</p>
</div>
<div class="fragment">
<p><em>(Collect conjectures)</em></p>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Three Explanations</h1>

</section>
<section class="slide level2">
<h2>The Three Standard Models</h2>
<p>Economists and philosophers have identified three main families of explanation for the college wage premium:</p>
<div class="fragment">
<p><strong>Human capital</strong>: college develops skills that are genuinely valuable to employers. The premium reflects those skills.</p>
</div>
<div class="fragment">
<p><strong>Selection</strong>: colleges admit people who are already more capable. The premium reflects the prior ability of graduates, not anything college does.</p>
</div>
<div class="fragment">
<p><strong>Signaling</strong>: college is a costly hurdle that demonstrates ability to employers. The premium reflects the signal, not the skills.</p>
</div>
<div class="fragment">
<p>These aren’t mutually exclusive, the truth may involve all three. But they have different implications, and the data can help us sort them out.</p>
</div>
</section>
<section class="slide level2">
<h2>A Useful Test</h2>
<p>Before accepting any explanation, it’s worth asking: <strong>what would the world look like if this were the whole story?</strong></p>
<div class="fragment">
<p>If human capital is everything, we’d expect partial degrees to have partial returns, three years should give three-quarters of the premium. We don’t see that.</p>
</div>
<div class="fragment">
<p>If selection is everything, we’d expect admission letters to be nearly as valuable as degrees, employers would pay for the signal of admission, not completion. We don’t see that either.</p>
</div>
<div class="fragment">
<p>If signaling is everything, we’d expect the premium even if college taught nothing useful. This one is harder to test directly.</p>
</div>
</section>
<section class="slide level2">
<h2>Your Turn: Which Is It?</h2>
<p>Which of these explanations do you find <strong>most plausible</strong>? What’s your best argument for your preferred view?</p>
<div class="fragment">
<p>And: is there an explanation that none of these models capture?</p>
</div>
<div class="fragment">
<p><em>(Discussion)</em></p>
</div>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>The Spence Model</h1>

</section>
<section class="slide level2">
<h2>Michael Spence</h2>
<p>Michael Spence won the Nobel Prize in economics in 2001, partly for this model.</p>
<div class="fragment">
<p>His 1973 paper “Job Market Signaling” showed how education could function as a <strong>costly signal</strong> even if it adds no productive skills whatsoever.</p>
</div>
<div class="fragment">
<p>We’ll use a simplified binary version of his model. He uses a continuous version that is perhaps more realistic, but the logic is the same.</p>
</div>
</section>
<section class="slide level2">
<h2>Structure of the Game</h2>
<p>Three players: <strong>Nature</strong>, <strong>Worker</strong>, and <strong>Employer</strong>.</p>
<div class="fragment">
<p><strong>Nature</strong> assigns each worker a type: <strong>High</strong> (productive, able) or <strong>Low</strong> (less so). The worker knows their type; the employer doesn’t.</p>
</div>
<div class="fragment">
<p><strong>Worker</strong> chooses: go to <strong>College</strong> or go to the <strong>Beach</strong> (i.e., skip college and enter the job market).</p>
</div>
<div class="fragment">
<p><strong>Employer</strong> sees the worker’s choice (College or Beach) but not their type. Based on that, they offer either a <strong>Good job</strong> or a <strong>Poor job</strong>.</p>
</div>
</section>
<section class="slide level2">
<h2>The Crucial Assumption</h2>
<p>For the model to work, college must be <strong>more costly</strong> for Low workers than for High workers.</p>
<div class="fragment">
<p>This doesn’t mean Low workers pay higher tuition. It means the effort, stress, and opportunity cost of completing a degree are greater for people with less ability.</p>
</div>
<div class="fragment">
<p>High workers find college demanding but manageable. Low workers find it genuinely painful, or can’t finish it at all.</p>
</div>
<div class="fragment">
<p>This differential cost is what makes college a potentially credible signal.</p>
</div>
</section>
<section class="slide level2">
<h2>Payoffs</h2>
<p>For the <strong>employer</strong>: they get 1 if they match correctly (Good to High, Poor to Low), and 0 otherwise.</p>
<div class="fragment">
<p>For the <strong>worker</strong>: a Poor job pays 0; a Good job pays 4. Going to the beach costs nothing. Going to college costs <strong>1 if you’re High</strong>, <strong>5 if you’re Low</strong>.</p>
</div>
</section>
<section class="slide level2">

<table class="caption-top">
<thead>
<tr class="header">
<th style="text-align: center;">Type</th>
<th style="text-align: center;">Choice</th>
<th style="text-align: center;">Offer</th>
<th style="text-align: center;">Worker</th>
<th style="text-align: center;">Employer</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: center;">High</td>
<td style="text-align: center;">College</td>
<td style="text-align: center;">Good</td>
<td style="text-align: center;">3</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">High</td>
<td style="text-align: center;">College</td>
<td style="text-align: center;">Poor</td>
<td style="text-align: center;">−1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">High</td>
<td style="text-align: center;">Beach</td>
<td style="text-align: center;">Good</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="even">
<td style="text-align: center;">High</td>
<td style="text-align: center;">Beach</td>
<td style="text-align: center;">Poor</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Low</td>
<td style="text-align: center;">College</td>
<td style="text-align: center;">Good</td>
<td style="text-align: center;">−1</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">Low</td>
<td style="text-align: center;">College</td>
<td style="text-align: center;">Poor</td>
<td style="text-align: center;">−5</td>
<td style="text-align: center;">1</td>
</tr>
<tr class="odd">
<td style="text-align: center;">Low</td>
<td style="text-align: center;">Beach</td>
<td style="text-align: center;">Good</td>
<td style="text-align: center;">4</td>
<td style="text-align: center;">0</td>
</tr>
<tr class="even">
<td style="text-align: center;">Low</td>
<td style="text-align: center;">Beach</td>
<td style="text-align: center;">Poor</td>
<td style="text-align: center;">0</td>
<td style="text-align: center;">1</td>
</tr>
</tbody>
</table>
</section>
<section class="slide level2">


<img data-src="19_files/figure-revealjs/fig-spence-1.png" width="384" class="r-stretch quarto-figure-center" id="fig-spence"><p class="caption">
Figure&nbsp;1: College or Beach signaling game
</p></section>
<section class="slide level2">
<h2>The Separating Equilibrium</h2>
<p>This game has a <strong>separating equilibrium</strong>:</p>
<ul>
<li class="fragment">High workers go to College; Low workers go to the Beach</li>
<li class="fragment">Employers offer Good jobs to College; Poor jobs to Beach</li>
</ul>
<div class="fragment">
<p>Let’s check that neither side wants to deviate.</p>
</div>
<div class="fragment">
<p>High workers: College + Good = 3. Could they get more by going to the Beach? Beach + Poor = 0. No.</p>
</div>
<div class="fragment">
<p>Low workers: Beach + Poor = 0. Could they do better by going to College? College + Good = −1. No, and College + Poor = −5. Definitely no.</p>
</div>
</section>
<section class="slide level2">
<h2>Why Low Workers Don’t Mimic</h2>
<p>This is the crucial point. Low workers <em>could</em> go to college to get the Good job. But they don’t, because for them the cost (5) exceeds the benefit (4).</p>
<div class="fragment">
<p>High workers find the same trade-off tilted the other way: cost (1) is much less than the benefit (4).</p>
</div>
<div class="fragment">
<p>The signal is <strong>credible precisely because it’s too expensive for Low types to fake</strong>. The degree acts as a hurdle that sorts workers without anyone explicitly verifying their type.</p>
</div>
</section>
<section class="slide level2">
<h2>What the Model Explains</h2>
<p>The Spence model handles several things previous models struggled with:</p>
<ul>
<li class="fragment"><strong>The sheepskin effect</strong>: finishing the degree is what sends the signal. Partial completion doesn’t clear the hurdle, so it earns no premium.</li>
<li class="fragment"><strong>Content-independence</strong>: the model doesn’t require any skill acquisition. Medieval epistemology counts just as much as accounting.</li>
<li class="fragment"><strong>Gate-keeping</strong>: there’s no need to restrict attendance, only to award degrees to those who complete, which is all we actually do.</li>
<li class="fragment"><strong>Scale</strong>: because the signal has to be costly enough to deter Low types, the model predicts a large premium, not a token one.</li>
</ul>
</section></section>
<section>
<section class="title-slide slide level1 center">
<h1>Three Challenges</h1>

</section>
<section class="slide level2">
<h2>Challenge 1: The Age Profile</h2>
<p>Recall: the college wage premium <strong>rises</strong> as workers age.</p>
<div class="fragment">
<p>Among workers aged 25–34, the premium is modest. Among workers aged 45–54, it’s much larger.</p>
</div>
<div class="fragment">
<p>This is puzzling for the signaling model.</p>
</div>
</section>
<section class="slide level2">
<h2>Why It’s Puzzling</h2>
<p>The Spence model works because employers can’t directly observe worker type, they rely on the college signal.</p>
<div class="fragment">
<p>But that assumption becomes increasingly implausible over time. After twenty years in the workforce, employers, and the market as a whole, should have <em>direct</em> evidence about a worker’s productivity.</p>
</div>
<div class="fragment">
<p>Performance reviews, promotions, colleagues’ assessments, track records: all of these provide information that should eventually replace the college signal.</p>
</div>
<div class="fragment">
<p><strong>Question for discussion</strong>: if employers can tell who’s good after a decade of work, why does the college signal get <em>more</em> valuable at ages 45–54, not less?</p>
</div>
</section>
<section class="slide level2">
<h2>Possible Responses</h2>
<p>There are some things the signaling theorist can say:</p>
<ul>
<li class="fragment">Employers at <strong>age 25–34</strong> are taking a risk; by 45–54, those risks have resolved and the better workers have been promoted, so the premium reflects career sorting, not the signal itself.</li>
<li class="fragment">The information sets in the model may not be information sets anymore, but the <strong>wage structure</strong> has already been set through long-term contracts, union agreements, or internal pay scales established earlier.</li>
</ul>
<div class="fragment">
<p>These responses are defensible, but they require adding assumptions the basic model doesn’t contain.</p>
</div>
</section>
<section class="slide level2">
<h2>Challenge 2: The Permanent Student Problem</h2>
<p>The model requires that college is <strong>more costly for Low workers than High workers</strong>.</p>
<div class="fragment">
<p>But think about who actually <em>enjoys</em> college most.</p>
</div>
<div class="fragment">
<p>In my experience, the students who thrived, who loved the reading, the dorm room debates, the seminars, the library, were not always the most productive future employees.</p>
</div>
<div class="fragment">
<p>The “permanent student” type: comfortable in an academic environment, happy to spend another year on a thesis, not easily stressed by exams. Are these the High types the model needs?</p>
</div>
</section>
<section class="slide level2">
<h2>The Problem Sharpened</h2>
<p>Spence’s model requires a tight correlation between <strong>how much you dislike college</strong> and <strong>how little employers want you</strong>.</p>
<div class="fragment">
<p>But the traits that make someone a good employee, reliability, practical judgment, client management, execution under deadlines, are not obviously the same traits that make college feel easier.</p>
</div>
<div class="fragment">
<p>Someone could be a wonderful accountant or nurse and find college genuinely painful. Someone could love and excel at academic life while being a poor fit for most professional environments.</p>
</div>
<div class="fragment">
<p>If the cost-type correlation doesn’t hold, the separating equilibrium breaks down: Low workers find college cheap enough to mimic High workers, and the signal loses its credibility.</p>
</div>
</section>
<section class="slide level2">
<h2>Question for Discussion</h2>
<p>Is the correlation tight enough to rescue the model?</p>
<div class="fragment">
<p>One response: whatever the mechanism, <em>in practice</em> college completion does predict job performance, so the equilibrium must be maintained by something.</p>
</div>
<div class="fragment">
<p>Another response: maybe the model was never fully accurate, and we’ve been in a messy partial-pooling situation all along, college screens out some Low types but not all.</p>
</div>
<div class="fragment">
<p>Where do you come down on this?</p>
</div>
</section>
<section class="slide level2">
<h2>Challenge 3: Degree Length and Cross-Country Evidence</h2>
<p>The Spence model treats degree length as the costly hurdle. This generates a prediction:</p>
<div class="fragment">
<p><strong>If you change the length of a degree, you should change who gets the premium.</strong></p>
</div>
<div class="fragment">
<p>And we have some natural experiments. The <strong>Bologna Process</strong> (from around 2000 onward) standardized European university degrees, in many countries shortening bachelor’s programs from 4–5 years to 3 years.</p>
</div>
<div class="fragment">
<p>What happened to the wage premium?</p>
</div>
</section>
<section class="slide level2">
<h2>What the Models Predict</h2>
<p>Under <strong>human capital</strong>: a shorter degree produces less skill. The premium should fall when degrees are shortened.</p>
<div class="fragment">
<p>Under <strong>signaling</strong>: the hurdle is recalibrated, employers simply update so that completing a 3-year degree now signals the same thing as completing a 4-year degree used to. The premium should persist roughly unchanged.</p>
</div>
<div class="fragment">
<p>Under <strong>selection</strong>: it doesn’t much matter, what’s selected for is the underlying ability, and degree length is just the filter.</p>
</div>
</section>
<section class="slide level2">
<h2>What the Evidence Suggests</h2>
<p>The evidence is somewhat mixed, but a few things stand out:</p>
<ul>
<li class="fragment">The UK has 3-year undergraduate degrees; the US has 4-year degrees. The wage premium is <strong>roughly comparable</strong> in both countries. This is hard to explain if an extra year of human capital acquisition is driving the US premium.</li>
<li class="fragment">In Germany, the shift from the 5-year Diplom to the 3-year Bologna Bachelor’s did not eliminate the graduate premium, though the Master’s degree has become increasingly expected, suggesting the hurdle shifted rather than disappeared.</li>
</ul>
</section>
<section class="slide level2">
<h2>A Cleaner Experiment: Los Andes</h2>
<p>The cross-country comparisons are suggestive but messy. Carolina Arteaga (2018) found a much cleaner test.</p>
<div class="fragment">
<p>In 2006, <strong>Universidad de los Andes</strong> in Colombia shortened its economics degree by about 20% and its business degree by about 14%. The entering class stayed the same size, with the same test scores and the same graduation rates.</p>
</div>
<div class="fragment">
<p>The <strong>signal</strong> was unchanged: same university, same degree title, same diploma. If signaling were the whole story, wages should have been unaffected.</p>
</div>
<div class="fragment">
<p>They were not. Graduates after the reform earned roughly <strong>16% less</strong> in economics and <strong>13% less</strong> in business.</p>
</div>
</section>
<section class="slide level2">
<h2>What Does This Tell Us?</h2>
<p>The Los Andes result is hard to square with a pure signaling model. The diploma looked the same before and after the reform, so the signal didn’t change. But the wages did.</p>
<div class="fragment">
<p>That suggests the lost coursework was doing something: building skills, or developing capacities that showed up in job performance.</p>
</div>
<div class="fragment">
<p>Arteaga found evidence for a specific mechanism: post-reform graduates performed worse during recruitment processes, and ended up placed at lower-quality firms.</p>
</div>
</section>
<section class="slide level2">
<h2>The Interpretation</h2>
<p>The evidence from degree-length changes is genuinely mixed:</p>
<div class="fragment">
<p>The <strong>Bologna reforms</strong> and the <strong>UK/US comparison</strong> suggest the premium tracks degree completion more than degree length, which favours a signaling or selection story.</p>
</div>
<div class="fragment">
<p>The <strong>Los Andes experiment</strong> suggests that cutting coursework does reduce wages, even when the signal is held fixed, which favours human capital.</p>
</div>
<div class="fragment">
<p>A reasonable reading: both mechanisms are at work. The degree functions partly as a signal and partly as a site of genuine skill acquisition, and the balance between these varies across institutions and labour markets.</p>
</div>
</section>
<section class="slide level2">
<h2>The Deeper Question</h2>
<p>Even if Spence’s model is broadly right, there’s a normative question lurking.</p>
<div class="fragment">
<p>If the premium is mostly a signal, then vast resources, tuition, four years of forgone income, the effort of millions of students, are being spent <strong>purely as a sorting device</strong>.</p>
</div>
<div class="fragment">
<p>The signal is privately rational (each student benefits from going to college) but <strong>socially wasteful</strong> (if everyone just skipped college, the same sorting could be achieved more cheaply, or not at all).</p>
</div>
<div class="fragment">
<p>This is one of the stranger equilibria we’ve encountered: everyone does the rational thing, and the outcome is a multi-trillion dollar institution that may not be educating anyone.</p>
</div>
</section>
<section class="slide level2">
<h2>Your View</h2>
<p>Which explanation strikes you as <strong>most important</strong> in explaining the college wage premium?</p>
<div class="fragment">
<p>And: does the answer change how you think about <strong>your own reasons for being at college</strong>?</p>
</div>
<div class="fragment">
<p><em>(Discussion)</em></p>
</div>
</section>
<section class="slide level2">
<h2>For Next Time</h2>
<p>We’ll start our look at more recent models of scientific practice.</p>
<p>From now on we’ll mostly be looking at <strong>agent-based models</strong>, where we don’t use representative individuals like High and Low, but model each individual separately.</p>


</section></section>
    </div>
  <div class="quarto-auto-generated-content" style="display: none;">
<p><img src="logo.png" class="slide-logo"></p>
<div class="footer footer-default">
<p>PHIL 342 | University of Michigan</p>
</div>
</div></div>

  <script>window.backupDefine = window.define; window.define = undefined;</script>
  <script src="../site_libs/revealjs/dist/reveal.js"></script>
  <!-- reveal.js plugins -->
  <script src="../site_libs/revealjs/plugin/quarto-line-highlight/line-highlight.js"></script>
  <script src="../site_libs/revealjs/plugin/pdf-export/pdfexport.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/menu.js"></script>
  <script src="../site_libs/revealjs/plugin/reveal-menu/quarto-menu.js"></script>
  <script src="../site_libs/revealjs/plugin/quarto-support/support.js"></script>
  

  <script src="../site_libs/revealjs/plugin/notes/notes.js"></script>
  <script src="../site_libs/revealjs/plugin/search/search.js"></script>
  <script src="../site_libs/revealjs/plugin/zoom/zoom.js"></script>
  <script src="../site_libs/revealjs/plugin/math/math.js"></script>
  <script>window.define = window.backupDefine; window.backupDefine = undefined;</script>

  <script>

      // Full list of configuration options available at:
      // https://revealjs.com/config/
      Reveal.initialize({
'controlsAuto': false,
'previewLinksAuto': true,
'pdfSeparateFragments': false,
'autoAnimateEasing': "ease",
'autoAnimateDuration': 1,
'autoAnimateUnmatched': true,
'jumpToSlide': true,
'menu': {"side":"left","useTextContentForMissingTitles":true,"markers":false,"loadIcons":false,"custom":[{"title":"Tools","icon":"<i class=\"fas fa-gear\"></i>","content":"<ul class=\"slide-menu-items\">\n<li class=\"slide-tool-item active\" data-item=\"0\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.fullscreen(event)\"><kbd>f</kbd> Fullscreen</a></li>\n<li class=\"slide-tool-item\" data-item=\"1\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.speakerMode(event)\"><kbd>s</kbd> Speaker View</a></li>\n<li class=\"slide-tool-item\" data-item=\"2\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.overview(event)\"><kbd>o</kbd> Slide Overview</a></li>\n<li class=\"slide-tool-item\" data-item=\"3\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.togglePdfExport(event)\"><kbd>e</kbd> PDF Export Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"4\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.toggleScrollView(event)\"><kbd>r</kbd> Scroll View Mode</a></li>\n<li class=\"slide-tool-item\" data-item=\"5\"><a href=\"#\" onclick=\"RevealMenuToolHandlers.keyboardHelp(event)\"><kbd>?</kbd> Keyboard Help</a></li>\n</ul>"}],"openButton":true},
'smaller': false,
 
        // Display controls in the bottom right corner
        controls: false,

        // Help the user learn the controls by providing hints, for example by
        // bouncing the down arrow when they first encounter a vertical slide
        controlsTutorial: false,

        // Determines where controls appear, "edges" or "bottom-right"
        controlsLayout: 'edges',

        // Visibility rule for backwards navigation arrows; "faded", "hidden"
        // or "visible"
        controlsBackArrows: 'faded',

        // Display a presentation progress bar
        progress: true,

        // Display the page number of the current slide
        slideNumber: 'c/t',

        // 'all', 'print', or 'speaker'
        showSlideNumber: 'all',

        // Add the current slide number to the URL hash so that reloading the
        // page/copying the URL will return you to the same slide
        hash: true,

        // Start with 1 for the hash rather than 0
        hashOneBasedIndex: false,

        // Flags if we should monitor the hash and change slides accordingly
        respondToHashChanges: true,

        // Push each slide change to the browser history
        history: true,

        // Enable keyboard shortcuts for navigation
        keyboard: true,

        // Enable the slide overview mode
        overview: true,

        // Disables the default reveal.js slide layout (scaling and centering)
        // so that you can use custom CSS layout
        disableLayout: false,

        // Vertical centering of slides
        center: false,

        // Enables touch navigation on devices with touch input
        touch: true,

        // Loop the presentation
        loop: false,

        // Change the presentation direction to be RTL
        rtl: false,

        // see https://revealjs.com/vertical-slides/#navigation-mode
        navigationMode: 'default',

        // Randomizes the order of slides each time the presentation loads
        shuffle: false,

        // Turns fragments on and off globally
        fragments: true,

        // Flags whether to include the current fragment in the URL,
        // so that reloading brings you to the same fragment position
        fragmentInURL: false,

        // Flags if the presentation is running in an embedded mode,
        // i.e. contained within a limited portion of the screen
        embedded: false,

        // Flags if we should show a help overlay when the questionmark
        // key is pressed
        help: true,

        // Flags if it should be possible to pause the presentation (blackout)
        pause: true,

        // Flags if speaker notes should be visible to all viewers
        showNotes: false,

        // Global override for autoplaying embedded media (null/true/false)
        autoPlayMedia: null,

        // Global override for preloading lazy-loaded iframes (null/true/false)
        preloadIframes: null,

        // Number of milliseconds between automatically proceeding to the
        // next slide, disabled when set to 0, this value can be overwritten
        // by using a data-autoslide attribute on your slides
        autoSlide: 0,

        // Stop auto-sliding after user input
        autoSlideStoppable: true,

        // Use this method for navigation when auto-sliding
        autoSlideMethod: null,

        // Specify the average time in seconds that you think you will spend
        // presenting each slide. This is used to show a pacing timer in the
        // speaker view
        defaultTiming: null,

        // Enable slide navigation via mouse wheel
        mouseWheel: false,

        // The display mode that will be used to show slides
        display: 'block',

        // Hide cursor if inactive
        hideInactiveCursor: true,

        // Time before the cursor is hidden (in ms)
        hideCursorTime: 5000,

        // Opens links in an iframe preview overlay
        previewLinks: false,

        // Transition style (none/fade/slide/convex/concave/zoom)
        transition: 'slide',

        // Transition speed (default/fast/slow)
        transitionSpeed: 'default',

        // Transition style for full page slide backgrounds
        // (none/fade/slide/convex/concave/zoom)
        backgroundTransition: 'fade',

        // Number of slides away from the current that are visible
        viewDistance: 3,

        // Number of slides away from the current that are visible on mobile
        // devices. It is advisable to set this to a lower number than
        // viewDistance in order to save resources.
        mobileViewDistance: 2,

        // The "normal" size of the presentation, aspect ratio will be preserved
        // when the presentation is scaled to fit different resolutions. Can be
        // specified using percentage units.
        width: 1050,

        height: 700,

        // Factor of the display size that should remain empty around the content
        margin: 0.1,

        math: {
          mathjax: 'https://cdn.jsdelivr.net/npm/mathjax@2.7.9/MathJax.js',
          config: 'TeX-AMS_HTML-full',
          tex2jax: {
            inlineMath: [['\\(','\\)']],
            displayMath: [['\\[','\\]']],
            balanceBraces: true,
            processEscapes: false,
            processRefs: true,
            processEnvironments: true,
            preview: 'TeX',
            skipTags: ['script','noscript','style','textarea','pre','code'],
            ignoreClass: 'tex2jax_ignore',
            processClass: 'tex2jax_process'
          },
        },

        // reveal.js plugins
        plugins: [QuartoLineHighlight, PdfExport, RevealMenu, QuartoSupport,

          RevealMath,
          RevealNotes,
          RevealSearch,
          RevealZoom
        ]
      });
    </script>
    
    <script>
      // htmlwidgets need to know to resize themselves when slides are shown/hidden.
      // Fire the "slideenter" event (handled by htmlwidgets.js) when the current
      // slide changes (different for each slide format).
      (function () {
        // dispatch for htmlwidgets
        function fireSlideEnter() {
          const event = window.document.createEvent("Event");
          event.initEvent("slideenter", true, true);
          window.document.dispatchEvent(event);
        }

        function fireSlideChanged(previousSlide, currentSlide) {
          fireSlideEnter();

          // dispatch for shiny
          if (window.jQuery) {
            if (previousSlide) {
              window.jQuery(previousSlide).trigger("hidden");
            }
            if (currentSlide) {
              window.jQuery(currentSlide).trigger("shown");
            }
          }
        }

        // hookup for slidy
        if (window.w3c_slidy) {
          window.w3c_slidy.add_observer(function (slide_num) {
            // slide_num starts at position 1
            fireSlideChanged(null, w3c_slidy.slides[slide_num - 1]);
          });
        }

      })();
    </script>

    <script id="quarto-html-after-body" type="application/javascript">
      window.document.addEventListener("DOMContentLoaded", function (event) {
        const tabsets =  window.document.querySelectorAll(".panel-tabset-tabby")
        tabsets.forEach(function(tabset) {
          const tabby = new Tabby('#' + tabset.id);
        });
        const isCodeAnnotation = (el) => {
          for (const clz of el.classList) {
            if (clz.startsWith('code-annotation-')) {                     
              return true;
            }
          }
          return false;
        }
        const onCopySuccess = function(e) {
          // button target
          const button = e.trigger;
          // don't keep focus
          button.blur();
          // flash "checked"
          button.classList.add('code-copy-button-checked');
          var currentTitle = button.getAttribute("title");
          button.setAttribute("title", "Copied!");
          let tooltip;
          if (window.bootstrap) {
            button.setAttribute("data-bs-toggle", "tooltip");
            button.setAttribute("data-bs-placement", "left");
            button.setAttribute("data-bs-title", "Copied!");
            tooltip = new bootstrap.Tooltip(button, 
              { trigger: "manual", 
                customClass: "code-copy-button-tooltip",
                offset: [0, -8]});
            tooltip.show();    
          }
          setTimeout(function() {
            if (tooltip) {
              tooltip.hide();
              button.removeAttribute("data-bs-title");
              button.removeAttribute("data-bs-toggle");
              button.removeAttribute("data-bs-placement");
            }
            button.setAttribute("title", currentTitle);
            button.classList.remove('code-copy-button-checked');
          }, 1000);
          // clear code selection
          e.clearSelection();
        }
        const getTextToCopy = function(trigger) {
          const outerScaffold = trigger.parentElement.cloneNode(true);
          const codeEl = outerScaffold.querySelector('code');
          for (const childEl of codeEl.children) {
            if (isCodeAnnotation(childEl)) {
              childEl.remove();
            }
          }
          return codeEl.innerText;
        }
        const clipboard = new window.ClipboardJS('.code-copy-button:not([data-in-quarto-modal])', {
          text: getTextToCopy
        });
        clipboard.on('success', onCopySuccess);
        if (window.document.getElementById('quarto-embedded-source-code-modal')) {
          const clipboardModal = new window.ClipboardJS('.code-copy-button[data-in-quarto-modal]', {
            text: getTextToCopy,
            container: window.document.getElementById('quarto-embedded-source-code-modal')
          });
          clipboardModal.on('success', onCopySuccess);
        }
          var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
          var mailtoRegex = new RegExp(/^mailto:/);
            var filterRegex = new RegExp("https:\/\/bweatherson\.github\.io\/W26-Phil342-site");
          var isInternal = (href) => {
              return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
          }
          // Inspect non-navigation links and adorn them if external
         var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool):not(.about-link)');
          for (var i=0; i<links.length; i++) {
            const link = links[i];
            if (!isInternal(link.href)) {
              // undo the damage that might have been done by quarto-nav.js in the case of
              // links that we want to consider external
              if (link.dataset.originalHref !== undefined) {
                link.href = link.dataset.originalHref;
              }
            }
          }
        function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
          const config = {
            allowHTML: true,
            maxWidth: 500,
            delay: 100,
            arrow: false,
            appendTo: function(el) {
                return el.closest('section.slide') || el.parentElement;
            },
            interactive: true,
            interactiveBorder: 10,
            theme: 'light-border',
            placement: 'bottom-start',
          };
          if (contentFn) {
            config.content = contentFn;
          }
          if (onTriggerFn) {
            config.onTrigger = onTriggerFn;
          }
          if (onUntriggerFn) {
            config.onUntrigger = onUntriggerFn;
          }
            config['offset'] = [0,0];
            config['maxWidth'] = 700;
          window.tippy(el, config); 
        }
        const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
        for (var i=0; i<noterefs.length; i++) {
          const ref = noterefs[i];
          tippyHover(ref, function() {
            // use id or data attribute instead here
            let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
            try { href = new URL(href).hash; } catch {}
            const id = href.replace(/^#\/?/, "");
            const note = window.document.getElementById(id);
            if (note) {
              return note.innerHTML;
            } else {
              return "";
            }
          });
        }
        const findCites = (el) => {
          const parentEl = el.parentElement;
          if (parentEl) {
            const cites = parentEl.dataset.cites;
            if (cites) {
              return {
                el,
                cites: cites.split(' ')
              };
            } else {
              return findCites(el.parentElement)
            }
          } else {
            return undefined;
          }
        };
        var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
        for (var i=0; i<bibliorefs.length; i++) {
          const ref = bibliorefs[i];
          const citeInfo = findCites(ref);
          if (citeInfo) {
            tippyHover(citeInfo.el, function() {
              var popup = window.document.createElement('div');
              citeInfo.cites.forEach(function(cite) {
                var citeDiv = window.document.createElement('div');
                citeDiv.classList.add('hanging-indent');
                citeDiv.classList.add('csl-entry');
                var biblioDiv = window.document.getElementById('ref-' + cite);
                if (biblioDiv) {
                  citeDiv.innerHTML = biblioDiv.innerHTML;
                }
                popup.appendChild(citeDiv);
              });
              return popup.innerHTML;
            });
          }
        }
      });
      </script>
    

</body></html>