# Probability and Decision Theory

## Probability

We'll start by going over the notion of probability that is used in decision theory. The best way to think about probability functions is by thinking about **measure** functions. Intuitively, a measure function is a non-negative **additive** function. That is, it is a function which only takes non-negative values, and where the value of a whole is equal to the sum of the value of the (non-overlapping) parts. In principle the domain of a measure function could be the size of any set, but we'll only consider functions with finite domains for now.

Such functions are frequently used in the real world. Consider, for instance, the functions from regions to their population and land mass. @tbl-uk-geography lists the (very approximate) population and land mass for England, Scotland, Wales and Northern Ireland.

  ------------------ ------------ -----------------------
                      Population         Land Mass
                      (Millions)   (Thousands of mi$^2$)
             England      50                50
            Scotland      5                 30
               Wales      3                  8
    Northern Ireland      2                  5
  ------------------ ------------ -----------------------

: Some statistics about the United Kingdom {#tbl-uk-geography}

The nice thing about tables like @tbl-uk-geography is that they give you a lot of information implicitly. You don't need a separate table to tell you that the combined population of England and Scotland is 55 million, or that the combined land mass of England and Wales is 58,000 square miles. Those (approximate) facts follow from the facts listed on the table, as well as the fact that populations and land masses are additive. Once you know the population of the parts, you know the population of the whole.

The next notion we need is that of a **normalised** measure function. A normalised measure is a measure where every function takes the value assigned to the largest whole is 1. We often use this notion when talking about proportions. @tbl-uk-geography-normal is a table listing, again approximately, the portion of the UK population and land mass in each of the four countries.

  ------------------ -------------- --------------
                       Population     Land Mass
                      (Proportion)   (Proportion)
             England      0.84           0.54
            Scotland      0.08           0.32
               Wales      0.05           0.09
    Northern Ireland      0.03           0.05
  ------------------ -------------- --------------

: A normalised verison of @tbl-uk-geography.

The way we turn the regular measure function into a normalised measure is by dividing each value on the earlier table by the value of whole. So the land mass of England is (about) 50,000 mi$^2$, and the land mass of the UK is (about) 93,000 mi$^2$, and $\nicefrac{50,000}{93,000}$ is about 0.54. So that's why we right 0.54 in the top right cell of the normalised measure table.

The last notion we need is that of a possibility space, or more formally, a **field** of propositions. Although these terms might be unfamiliar, the notion should be very familiar; it is just what we represent with a truth table. We will identify, for these purposes, propositions with sets of possible worlds. Then a field of propositions is a set of propositions such that whenever $A$ and $B$ are in the set, so are $\neg A$ and $A \wedge B$. This is, of course, just what we see with truth tables. Whenever you can represent two propositions on a truth table, you can represent their conjunction and each of their negations. Just like with truth-tables, we'll only consider finite fields. It's possible to extend this to cover any set-sized partition of possibility space, but we'll ignore such complications for now.

A **Probability function** is just a normalised measure on a possibility space. That is, it is a function satisfying these two conditions, where $A$ and $B$ are any propositions, and $T$ is a logical truth.

- $0 \leq \Pr(A) \leq 1 = \Pr(T)$
- If $A$ and $B$ can't both be true, then $\Pr(A \vee B) = \Pr(A) + \Pr(B)$.

We normally suppose that any rational agent has **credences** over the space of (salient) epistemic possibilities, and these credences form a probability function.

In any finite field of propositions, there will be some **atoms**. These are propositions such that no stronger consistent proposition is in the field. (Some, but not all, infinite fields are atomic.) We will use these atoms a lot. I'll use the variable $w$ to range over atoms, reminding us that for practical purposes, atoms behave a lot like *worlds*. They aren't worlds, of course; they only settle the truth values of a handful of propositions. But they are divisions of possibility space that are maximally precise for present purposes. That is, they are being treated as worlds. On a pragmatist approach to modality, there's no more to being a world than to be treated as a world in the right circumstances, and thinking about probability encourages, I think, such a pragmatist approach.

## Conditional Probability

So far we've talked simply about the probability of various propositions. But sometimes we're not interested in the absolute probability of a proposition, we're interested in its **conditional** probability. That is, we're interested in the probability of the proposition *assuming* or *conditional on* some other proposition obtaining.

It isn't too hard to visualise how conditional probability works if we think of a possibility space simply as a truth table, so a measure over a possibility space is simply a measure over on the truth table. @tbl-tt-first how we might represent a simple probability function, defined over the Boolean combinations of three propositions, if we're thinking about things this way.

   $p$   $q$   $r$  
  ----- ----- ----- --------
    T     T     T    0.0008
    T     T     F    0.008
    T     F     T     0.08
    T     F     F     0.8
    F     T     T    0.0002
    F     T     F    0.001
    F     F     T     0.01
    F     F     F     0.1

: A truth table, with measures {#tbl-tt-first}

The way to read @tbl-tt-first is that each row defines a world. The characteristics of the world are just the truth values of three salient propositions: $p, q, r$. If T is shown underneath the name of a proposition, that means the proposition is true in the world, and if an F is shown, it mans the proposition is false. So the third line is the world where $p$ and $r$ are true, and $q$ is false. To the right of the vertical line is the probability of that world. We can work out the probability of any proposition that is true at multiple worlds by adding up the probabilities of the worlds where it is true. So $\Pr(q) = 0.0008 + 0.008 + 0.0002 + 0.001 = 0.01$.

Now let's see what happens when we look at conditional probabilities, i.e., probabilities you get from assuming some particular proposition is true. If we assume that $B$ is true, then we should 'zero out', i.e. assign probability 0, to all the possibilities where $B$ doesn't obtain. We're now left with a measure over only the $B$-possibilities. The problem is that it isn't a normalised measure. The values will only sum to $\Pr(B)$, not to 1. We need to renormalise. So we divide by $\Pr(B)$ and we get a probability back. In a formula, we're left with

\begin{equation*}
Pr(A|B) = \frac{\Pr(A \wedge B)}{\Pr(B)}
\end{equation*}

Assume now that we're trying to find the conditional probability of $p$ given $q$ in the above table. We could do this in two different ways. First, we could set the probability of any line where $q$ is false to 0. So we will get @tbl-tt-second.

   $p$   $q$   $r$  
  ----- ----- ----- --------
    T     T     T    0.0008
    T     T     F    0.008
    T     F     T      0
    T     F     F      0
    F     T     T    0.0002
    F     T     F    0.001
    F     F     T      0
    F     F     F      0

: What happens to @tbl-tt-first if we 0 out $\neg q$ {#tbl-tt-second}

The numbers don't sum to 1 any more. They sum to 0.01. So we need to divide everything by 0.01. It's sometimes easier to conceptualise this as multiplying by $\nicefrac{1}{\Pr(q)}$, i.e. by multiplying by 100. Then we'll end up with @tbl-tt-third.

   $p$   $q$   $r$  
  ----- ----- ----- ------
    T     T     T    0.08
    T     T     F    0.8
    T     F     T     0
    T     F     F     0
    F     T     T    0.02
    F     T     F    0.1
    F     F     T     0
    F     F     F     0

: What happens to @tbl-tt-second if renormalise {#tbl-tt-third}

And since $p$ is true on the top two lines of @tbl-tt-third, the 'new' probability of $p$ is 0.88. That is, the conditional probability of $p$ given $q$ is 0.88. As we were writing things above, $\Pr(p | q) = 0.88$.

Alternatively we could just use the formula given above. Just adding up rows gives us the following numbers. 

\begin{align*}
\Pr(p \wedge q) &= 0.0008 + 0.008 = 0.0088 \\
\Pr(q) &= 0.0008 + 0.008 + 0.0002 + 0.001 = 0.01
\end{align*}

Then we can apply the formula. 

\begin{align*}
\Pr(p | q) &= \frac{\Pr(p \wedge q)}{\Pr(q)} \\
&= \frac{0.0088}{0.01} \\
&= 0.88
\end{align*}

## Bayes Theorem

This is a bit of a digression from what we're really focussing on in game theory, but it's important for understanding how conditional probabilities work. It is often easier to calculate conditional probabilities in the 'inverse' direction to what we are interested in. That is, if we want to know $\Pr(A | B)$, it might be much easier to discover $\Pr(B | A)$. In these cases, we use Bayes Theorem to get the right result. I'll state Bayes Theorem in two distinct ways, then show that the two ways are ultimately equivalent. 

\begin{align*}
\Pr(A|B) &= \frac{\Pr(B|A) \Pr(A)}{\Pr(B)} \\
&= \frac{\Pr(B|A) \Pr(A)}{\Pr(B|A)Pr(A) + \Pr(B|\neg A)Pr(\neg A)}
\end{align*}

These are equivalent because $\Pr(B) = \Pr(B|A)Pr(A) + \Pr(B|\neg A)\Pr(\neg A)$. Since this is an independently interesting result, it's worth going through the proof of it. First note that 

\begin{align*}
\Pr(B|A)\Pr(A) &= \frac{\Pr(A \wedge B)}{\Pr(A)} \Pr(A) \\
&= \Pr(A \wedge B) \\
\\
\Pr(B|\neg A)\Pr(\neg A) &= \frac{\Pr(\neg A \wedge B)}{\Pr\neg (A)} \Pr(\neg A) \\
&= \Pr(\neg A \wedge B)
\end{align*}

Adding those two together we get 

\begin{align*}
\Pr(B|A)\Pr(A) + \Pr(B|\neg A)\Pr(\neg A) &= \Pr(A \wedge B) + \Pr(\neg A \wedge B) \\
&= \Pr((A \wedge B) \vee (\neg A \wedge B)) \\
&= \Pr(B)
\end{align*}

The second line uses the fact that $A \wedge B$ and $\neg A \wedge B$ are inconsistent. And the third line uses the fact that $(A \wedge B) \vee (\neg A \wedge B)$ is equivalent to $A$. So we get a nice result, one that we'll have occasion to use a bit in what follows. 

\begin{equation*}
\Pr(B) = \Pr(B|A)\Pr(A) + \Pr(B|\neg A)\Pr(\neg A)
\end{equation*}

 So the two forms of Bayes Theorem are the same. We'll often find ourselves in a position to use the second form.

One kind of case where we have occasion to use Bayes Theorem is when we want to know how significant a test finding is. So imagine we're trying to decide whether the patient has disease D, and we're interested in how probable it is that the patient has the disease conditional on them returning a test that's positive for the disease. We also know the following background facts.

- In the relevant demographic group, 5% of patients have the disease.
- When a patient has the disease, the test returns a position result 80% of the time
- When a patient does not have the disease, the test returns a negative result 90% of the time

So in some sense, the test is fairly reliable. It usually returns a positive result when applied to disease carriers. And it usually returns a negative result when applied to non-carriers. But as we'll see when we apply Bayes Theorem, it is very unreliable in another sense. So let $A$ be that the patient has the disease, and $B$ be that the patient returns a positive test. We can use the above data to generate some 'prior' probabilities, i.e. probabilities that we use prior to getting information about the test.

- $\Pr(A) = 0.05$, and hence $\Pr(\neg A) = 0.95$
- $\Pr(B | A) = 0.8$
- $\Pr(B | \neg A) = 0.1$

Now we can apply Bayes theorem in its second form. 

\begin{align*}
\Pr(A|B) &= \frac{\Pr(B|A) \Pr(A)}{\Pr(B|A)\Pr(A) + \Pr(B|\neg A)\Pr(\neg A)} \\
&= \frac{0.8 \times 0.05}{0.08 \times 0.05 + 0.1 \times 0.95} \\
&= \frac{0.04}{0.04 + 0.095} \\
&= \frac{0.04}{0.135} \\
&\approx& 0.296
\end{align*}

So in fact the probability of having the disease, conditional on having a positive test, is less than 0.3. So in that sense the test is quite unreliable.

This is actually a quite important point. The fact that the probability of $B$ given $A$ is quite high does not mean that the probability of $A$ given $B$ is equally high. By tweaking the percentages in the example I gave you, you can come up with cases where the probability of $B$ given $A$ is arbitrarily high, even 1, while the probability of $A$ given $B$ is arbitrarily low.

Confusing these two conditional probabilities is sometimes referred to as the *Prosecutors' fallacy*, though it's not clear how many actual prosecutors are guilty of it. The thought is that some prosecutors start with the premise that the probability of the defendant's blood (or DNA or whatever) matching the blood at the crime scene, conditional on the defendant being innocent, is 1 in a billion (or whatever it exactly is). They conclude that the probability of the defendant being innocent, conditional on their blood matching the crime scene, is about 1 in a billion. Because of derivations like the one we just saw, that is a clearly invalid move.

A more striking real world example comes from the analysis of soccer carried out by Charles Reep and Charles Hughes. (Reep and Hughes worked separately, but they reached similar conclusions by similar means.) They watched many games, and tracked each of the possessions (meaning a period of time where one team has control of the ball). They counted how many passes took place in each possession, and whether the possession resulted in a goal. They noted that the vast majority of the goals came from very short possessions, ones involving three or fewer passes. From this they concluded that soccer teams should be direct; kicking the ball to forwards as soon as possible to try to score from a short possession. Hughes became technical director of the Football Association in England, where he spread this idea of how to play soccer across the country.

You may be able to spot the error in their reasoning already, but if not let's work through a fictionalised version to see the problem. (The numbers I'm using are made up, though I think the scale roughly matches what Reep and Hughes found.) Divide all possessions into short (1-3 passes), medium (4-7 passes) and long (8+ passes). Imagine that we observed a bunch of games, and recorded the data in @tbl-soccer.

            Goal   No Goal
  -------- ------ ---------
     Short   78      822
    Medium   12      48
      Long   10      30

: Some imagined data for how soccer goals are scored {#tbl-soccer}

As you can see, most goals come from short possessions. But you shouldn't get excited by finding your team has had a short possession; over 90% of short possessions go nowhere. On the other hand, medium to long possessions often end in goals. In @tbl-soccer-percent I've added another column to @tbl-soccer to make this clear.

            Goal   No Goal   Success %
  -------- ------ --------- -----------
     Short   78      822        8.7
    Medium   12      48         20
      Long   10      30         25

: A version of @tbl-soccer with success probability added.

The longer a possession is, the higher the frequency that it ends in a goal. I'm not sure in real soccer it is as dramatic as the numbers I gave you. (And in fact at high levels of soccer not nearly this high a percentage of possessions end in goals.) But I am confident that (at least at high levels, at most times in the history of soccer) the broad pattern I've outlined here is correct. Most goals come from short possessions, but short possessions lead to fewer goals, on average, than long possessions. Anyone who has taken a probability class should know that this suggests aiming for longer possessions rather than shorter ones, but apparently the England hierarchy didn't take that lesson for several decades.

## Expected Value

One very convenient notion to define using a probability function is that of an **expected value**. Say that a **random variable** is any function from possibilities to real numbers. We usually designate random variables with capital letters. So expressions like $X=x$, which you'll often see in probability textbooks, means that the random variable $X$ takes real value $x$.

The expected value of a random variable is calculated using the following formula.

\begin{equation*}
E(X) = \sum_w \Pr(w)X(w)
\end{equation*}

Remember that $w$ is a variable that ranges over atoms. So the summation here is over the atoms in the field. $\Pr(w)$ is the probability of that atom obtaining, and $X(w)$ is the value of the random variable at $w$. Here's a worked example to make it clearer.

Let our random variable $X$ be the number of children of the next person to walk through the door. Let's assume that the department contains 10 people; 2 of whom have three children, 3 of whom have two children, 3 of whom have one child, and 2 are childless. Each member of the department is equally likely to walk through the door, and no one else is going to. So the probability of any given member of the department walking through the door is $\nicefrac{1}{10}$. Then the expected value of $X$, i.e., $E(X)$, is:

\begin{align*}
\nicefrac{1}{10} \times 3 + \nicefrac{1}{10} \times 3 &+ \\
\nicefrac{1}{10} \times 2 + \nicefrac{1}{10} \times 2 + \nicefrac{1}{10} \times 2 &+ \\
\nicefrac{1}{10} \times 1 + \nicefrac{1}{10} \times 1 + \nicefrac{1}{10} \times 1 &+ \\
\nicefrac{1}{10} \times 0 + \nicefrac{1}{10} \times 0 &= 1.5 \\
\end{align*}

Note that the expected value of $X$ is *not* the value we 'expect', in the ordinary sense, $X$ to take. We can be pretty sure that $X$'s value will be an integer, so it won't be 1.5, for instance! That is to say, 'expected value' is a term of art.

As well as 'absolute' expected values, we can also define conditional expected values, as follows:

\begin{equation*}
E(X | p) = \sum_w \Pr(w | p)X(w)
\end{equation*}

I won't go through the proof of this, but it turns out that conditional expected values satisfy a nice theorem. Let $\{p_1, \dots, p_n\}$ be a partition of possibility space. Then the following holds.

\begin{equation*}
E(X) = \sum_{i=1}^n \Pr(p_i) E(X | p_i)
\end{equation*}

Here are a few of immediate corrollaries of that result.

\begin{align*}
E(X) -E(Y) &= E(X - Y) \\
&= \sum_{i=1}^n \Pr(p_i) (E(X | p_i) - E(Y | p_i)) \\
&= \sum_{i=1}^n \Pr(p_i) (E((X - Y) | p_i))
\end{align*}

Often we know more about the difference between two expected values than we do about the absolute value of either. For instance, if we are comparing the expected values of taking and declining a small bet, we can figure out which action has a higher expected value without figuring out the expected value of either, which presumably depends on all sorts of facts about how our life might (probably) go. But as long as we can work out the difference in expected value between the two acts conditional on each $p_i$, and the probability of each $p_i$, we can work out at least which has a higher expected value, and by how much.

## Orthodox Decision Theory

Given all that, it is fairly easy to summarise orthodox decision theory.

- Rational agents have a credence function over salient alternatives that is identical to some probability function $\Pr$.
- Rational agents also have a real-valued utility function $U$ over salient outcomes.
- The rational action for such an agent to do is the action that maximises **expected** utility, i.e., maximises the expected value of $U$ relative to that function $\Pr$.

Next time we'll start with an application of those ideas that leads to the most central concept in game theory.
