---
title: "Answers to Translation Questions"
format:
    html: default
---

## Questions

1. Either it will snow or it will rain, but not both.
2. If it's sunny, we'll go to the beach and have a picnic.
3. We'll leave unless it rains.
4. You'll pass if you study, and you'll fail if you don't.
5. If it rains on Monday and Tuesday, then the game will be postponed.
6. Either it will rain on Monday and Tuesday, or it will be sunny on Wednesday.
7. It will rain on Monday or Tuesday, but not on both days.
8. If either Alice or Bob comes to the party, then if Carol comes, David won't come.

## Either it will snow or it will rain, but not both.

S = It will snow   
R = It will rain

- $(S \vee R) \wedge \neg(S \wedge R)$

## If it's sunny, we'll go to the beach and have a picnic.

S = It is sunny   
B = Go to beach   
P = Have picnic

- $S \rightarrow (B \wedge P)$

## We'll leave unless it rains.

L = We leave   
R = It rains

Note that _unless_ basically means _if not_. So the sentence means _We'll leave if it doesn't rain_, i.e.,

- $\neg R \rightarrow L$

## You'll pass if you study, and you'll fail if you don't.

P = You pass    
S = You study hard

- $(S \rightarrow P) \wedge (\neg S \rightarrow \neg P)$, equivalently
- $P \leftrightarrow S$

## If it rains on Monday and Tuesday, then the game will be postponed.

M = Monday rain    
T = Tuesday rain    
P = Game is postponed

- $(M \wedge T) \rightarrow P$

## Either it will rain on Monday and Tuesday, or it will be sunny on Wednesday.

M = Monday rain    
T = Tuesday rain    
W = Wednesday **sunny**

- $(M \wedge T) \vee W$

## It will rain on Monday or Tuesday, but not on both days.

M = Monday rain    
T = Tuesday rain

- $(M \vee T) \wedge \neg (M \wedge T)$

## If either Alice or Bob comes to the party, then if Carol comes, David won't come.

A = Alice comes to party    
B = Bob comes to party    
C = Carol comes to party    
D = David comes to party

- $(A \vee B) \rightarrow (C \rightarrow \neg D)$